## 1 .Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [29]:
import numpy as np
def Vandermonde(n,increasing):
    print("N value is :",n)
    final = []
    if(increasing == True):        
        for i in  range(1,n+1):
            res = []
            for j in range(0,n+1):
                res.append(i**j)
            final.append(res)
        print("Vandermonde matrix when increasing is : True \n",np.array(final))
    if(increasing == False):
        for i in  range(1,n+1):
            res = []
            for j in range(n,-1,-1):
                res.append(i**j)
            final.append(res)
        print("Vandermonde matrix when increasing is : False \n",np.array(final))
    
Vandermonde(int(input()),increasing = True)    
Vandermonde(int(input()),increasing = False)

5
N value is : 5
Vandermonde matrix when increasing is : True 
 [[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]]
5
N value is : 5
Vandermonde matrix when increasing is : False 
 [[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]


# 2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

In [49]:
def my_avg(window_size):
    inp = list(map(int,input().split()))
    n   = len(inp)
    c = 0
    for i in range(0,n-window_size+1):
        summ = 0
        for j in range(i,window_size+i):
            #print(inp[j])
            summ += inp[j]
        c = c+1    
        print(c,"avg  Output is : ",int(summ/window_size))
            
        
for _ in range(2):
    my_avg(int(input("Enter window_size  : ")))
    print("=="*30)

Enter window_size  : 4
10 20 30 40 50 60 70 80 90 100
1 avg  Output is :  25
2 avg  Output is :  35
3 avg  Output is :  45
4 avg  Output is :  55
5 avg  Output is :  65
6 avg  Output is :  75
7 avg  Output is :  85
Enter window_size  : 3
3 5 7 2 8 10 11 65 72 81 99 100 150
1 avg  Output is :  5
2 avg  Output is :  4
3 avg  Output is :  5
4 avg  Output is :  6
5 avg  Output is :  9
6 avg  Output is :  28
7 avg  Output is :  49
8 avg  Output is :  72
9 avg  Output is :  84
10 avg  Output is :  93
11 avg  Output is :  116


In [52]:
(99+100+150)//3

116

In [ ]:
3 5 7 2 8 10 11 65 72 81 99 100 150